version: "3.7"

volumes:
  local_media_data: { }

networks:
  default:
    external:
      name: osv-proxy_osv_network

services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2021-01-08T21-18-21Z
    entrypoint: minio server /data
    ports:
      - "9090:9000"
    env_file:
      - .envs/.minio
    volumes:
      - local_media_data:/data

  web:
    build: .
    container_name: web
    volumes:
      - .:/code
    command:
      - /deploy.sh
    ports:
      - "8000:8000"
    env_file:
      - .envs/.web
    depends_on:
      - minio