version: "3.7"

volumes:
  local_media_data: { }

services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2021-01-08T21-18-21Z
    entrypoint: minio server /data
    ports:
      - "9090:9000"
    env_file:
      - .envs/.minio
    volumes:
      - local_media_data:/data

  web:
    build: .
    container_name: web
    command: "python manage.py migrate && python manage.py collectstatic --no-input && gunicorn pausas_activas.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .envs/.web
    depends_on:
      - minio